// account
export const ACCCOUNTS_ERROR_CAUGHT = 'ACCCOUNTS_ERROR_CAUGHT';
export const ACCCOUNTS_GET_REQUEST = 'ACCCOUNTS_GET_REQUEST';
export const ACCCOUNTS_GET_SUCCESS = 'ACCCOUNTS_GET_SUCCESS';
export const ACCCOUNTS_POST_REQUEST = 'ACCCOUNTS_POST_REQUEST';
export const ACCCOUNTS_POST_SUCCESS = 'ACCCOUNTS_POST_SUCCESS';
export const ACCCOUNTS_PUT_REQUEST = 'ACCCOUNTS_PUT_REQUEST';
export const ACCCOUNTS_PUT_SUCCESS = 'ACCCOUNTS_PUT_SUCCESS';

// user
export const USER_ERROR_CAUGHT = 'USER_ERROR_CAUGHT';
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_POST_REQUEST = 'USER_POST_REQUEST';
export const USER_POST_SUCCESS = 'USER_POST_SUCCESS';
export const USER_PUT_REQUEST = 'USER_PUT_REQUEST';
export const USER_PUT_SUCCESS = 'USER_PUT_SUCCESS';
