// account
export const ACCCOUNTS_ERROR_CAUGHT = 'ACCCOUNTS_ERROR_CAUGHT';
export const ACCCOUNTS_GET_REQUEST = 'ACCCOUNTS_GET_REQUEST';
export const ACCCOUNTS_GET_SUCCESS = 'ACCCOUNTS_GET_SUCCESS';
export const ACCCOUNTS_POST_REQUEST = 'ACCCOUNTS_POST_REQUEST';
export const ACCCOUNTS_POST_SUCCESS = 'ACCCOUNTS_POST_SUCCESS';
export const ACCCOUNTS_PUT_REQUEST = 'ACCCOUNTS_PUT_REQUEST';
export const ACCCOUNTS_PUT_SUCCESS = 'ACCCOUNTS_PUT_SUCCESS';

// account
export const SITES_ERROR_CAUGHT = 'SITES_ERROR_CAUGHT';
export const SITES_GET_REQUEST = 'SITES_GET_REQUEST';
export const SITES_GET_SUCCESS = 'SITES_GET_SUCCESS';
export const SITES_POST_REQUEST = 'SITES_POST_REQUEST';
export const SITES_POST_SUCCESS = 'SITES_POST_SUCCESS';
export const SITES_PUT_REQUEST = 'SITES_PUT_REQUEST';
export const SITES_PUT_SUCCESS = 'SITES_PUT_SUCCESS';

// user
export const SET_NETLIFY_API_TOKEN = 'SET_NETLIFY_API_TOKEN';
export const USER_ERROR_CAUGHT = 'USER_ERROR_CAUGHT';
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_POST_REQUEST = 'USER_POST_REQUEST';
export const USER_POST_SUCCESS = 'USER_POST_SUCCESS';
export const USER_PUT_REQUEST = 'USER_PUT_REQUEST';
export const USER_PUT_SUCCESS = 'USER_PUT_SUCCESS';
