// account
export const ACCCOUNT_GET_REQUEST = 'ACCCOUNT_GET_REQUEST';
export const ACCCOUNT_GET_SUCCESS = 'ACCCOUNT_GET_SUCCESS';
export const ACCCOUNT_POST_REQUEST = 'ACCCOUNT_POST_REQUEST';
export const ACCCOUNT_POST_SUCCESS = 'ACCCOUNT_POST_SUCCESS';
export const ACCCOUNT_PUT_REQUEST = 'ACCCOUNT_PUT_REQUEST';
export const ACCCOUNT_PUT_SUCCESS = 'ACCCOUNT_PUT_SUCCESS';
